/** 渲染进程可调用的固定 IPC 通道。 */
export const ipcChannels = {
  getDevices: "devices:get",
  refreshDevices: "devices:refresh",
  devicesChanged: "devices:changed",
  getRecordingState: "recording:get-state",
  recordingStateChanged: "recording:state-changed",
  getRecordingArtifact: "recording:get-artifact",
  recordingArtifactChanged: "recording:artifact-changed",
  getRecordingLibrary: "recording-library:get",
  refreshRecordingLibrary: "recording-library:refresh",
  deleteRecordings: "recording-library:delete",
  recordingLibraryChanged: "recording-library:changed",
  requestLivePreview: "recording:request-live-preview",
  livePreviewPort: "recording:live-preview-port",
  getMirrorState: "mirroring:get-state",
  mirrorStateChanged: "mirroring:state-changed",
  startMirroring: "mirroring:start",
  stopMirroring: "mirroring:stop",
  deviceControl: "mirroring:control",
  startRecording: "recording:start",
  stopRecording: "recording:stop",
  exportRecording: "recording:export",
  openRecordingFolder: "recording:open-folder",
  getSettings: "settings:get",
  setSettings: "settings:set",
  chooseRecordingsDirectory: "settings:choose-recordings-directory",
  controlWindow: "window:control"
} as const;
